spring.application.name=academia-web

spring.datasource.url=jdbc:postgresql://localhost:5432/academia_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=8W5fOe8vK7n5rWv6mQJ9YdK0J0bXgA2uY3fP8mL4sNc=
jwt.expiration=7200000